soong: Forbidden pkg-config again
* Fixes kernel build failure in Arch Linux due to
  missing header file error even if it exists

Log:
/home/someone5678/android/TheParasiteProject/kernel/sony/sm8550/scripts/dtc/yamltree.c:9:10: fatal error: 'yaml.h' file not found
         ^~~~~~~~

Change-Id: I5a1fab8f1d741eb2bcf7b1ca0279816e531a052d